### ISSUE TITLE
Compiler doesn't work with npm3 flattened dependencies

### ISSUE THREAD

**Issue by dustyjewett** [knksmith57/hbs-cjs-compiler#3]
npm3 now installs a flattened version of dependencies... so handlebars is no longer in the hbs-cjs-compiler/node_modules directory.

AFAIK, directly referencing node_modules is now considered very deprecated... Not entirely certain how to get around it for this plugin.

**Comment by knksmith57** [comment]
Thanks for the heads up! I'm short on bandwidth today but will take a crack at it this weekend. This shouldn't be too hard to fix; I kind of hacked together that resolver the first time anyway.

**Comment by knksmith57** [comment]
@dustyjewett this seems to be working for me now with both npm v2 and v3. I'm going to write some much-needed test coverage and then cut a `1.0.0` release with the updates.

I'll keep you posted when this is done. Thanks again for the heads up!
